[package]
name = "solana_smart_contract"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
solana-program = "=1.18.2" 
spl-token = { version = "4.0.0", features = ["no-entrypoint"] }

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
